- minos/common/__init__.py
- minos/common/configuration/__init__.py
- minos/common/configuration/config.py
- minos/common/exceptions.py
- minos/common/importlib.py
- minos/common/logs.py
- minos/common/messages/__init__.py
- minos/common/messages/request.py
- minos/common/messages/response.py
- minos/common/model/__init__.py
- minos/common/model/aggregate.py
- minos/common/model/fields.py
- minos/common/model/types.py
- minos/common/protocol/__init__.py
- minos/common/protocol/abstract.py
- minos/common/protocol/avro.py
- minos/common/storage/__init__.py
- minos/common/storage/abstract.py
- minos/common/storage/lmdb.py
- tests/modelClasses.py
- tests/test_aggregate_model.py
- tests/test_avro_encoder_decoder.py
- tests/test_config.py
- tests/test_importlib.py
- tests/test_messages.py
- tests/test_storage_lmdb.py
This pull request is intended to resolve the #13 issue.
> Issue #13 (start using relative imports instead of absolute ones)

- minos/common/model/fields.py
- tests/test_common/test_model/test_fields.py
This pull request resolves #11
> Issue #11 (support dict by model field)

- minos/common/model/types.py
- tests/test_common/test_model/test_types.py
> Issue #21 (minos.common.models.types tests)

- minos/common/model/model.py
- tests/modelClasses.py
- tests/test_common/test_model/test_model.py
> Issue #25 (set atributes on the MinosModel constructor)

- minos/common/__init__.py
- minos/common/model/__init__.py
- minos/common/model/fields.py
- minos/common/model/types.py
- tests/modelClasses.py
- tests/test_common/test_model/test_fields.py
- tests/test_common/test_model/test_model.py
- tests/test_common/test_model/test_types.py
> Issue #7 (implement reference field)

- minos/common/model/fields.py
- minos/common/model/model.py
- tests/test_common/test_model/test_fields.py
- tests/test_common/test_model/test_model.py
> Issue #24 (implement equals)

- minos/common/__init__.py
- minos/common/exceptions.py
- minos/common/model/fields.py
- minos/common/model/model.py
- minos/common/model/types.py
- tests/modelClasses.py
- tests/test_common/test_exceptions.py
- tests/test_common/test_model/test_fields.py
- tests/test_common/test_model/test_model.py
- tests/test_common/test_model/test_types.py
> Issue #30 (required field exception)

- minos/common/model/fields.py
- tests/modelClasses.py
- tests/test_common/test_model/test_fields.py
- tests/test_common/test_model/test_model.py
> Issue #34 (refactor `minos.common.ModelField` value setter)

- minos/common/__init__.py
- minos/common/exceptions.py
- minos/common/model/fields.py
- minos/common/model/model.py
- tests/modelClasses.py
- tests/test_common/test_exceptions.py
- tests/test_common/test_model/test_fields.py
- tests/test_common/test_model/test_model.py
> Issue #28 (custom attribute validators)

- minos/common/model/fields.py
- tests/modelClasses.py
- tests/test_common/test_model/test_fields.py
- tests/test_common/test_model/test_model.py
> #52 (dictionary keys must be strings)

- minos/common/broker.py
- tests/test_broker.py
> #62 (base broker service class)

- minos/common/configuration/config.py
- tests/test_config.py
- tests/test_config.yaml
MinosConfig queue parameter must support the attribute "retry" #51
> Minos Config Queue Retry parameter

- minos/common/broker.py
Create the Base class for Commands #56
Create the Base class for Events #55
> Broker Base classes for Event/Command

- minos/common/__init__.py
- minos/common/broker.py
- tests/test_broker.py
> #128 (Expose `minos.common.broker`)

- minos/common/testing.py
> #153 (unique identifier test database)

- minos/common/database.py
- minos/common/repository/entries.py
- minos/common/repository/pg.py
- minos/common/setup.py
- tests/test_common/test_repository/test_entries.py
- tests/test_common/test_repository/test_memory.py
- tests/test_common/test_repository/test_pg.py
> #148 (`created_at` on `aggregate_events` table)

- minos/common/configuration/config.py
- tests/test_common/test_configuration/test_config.py
- tests/test_config.yml
> #155 (`snapshot` on `minos.common.MinosConfig`)

- minos/common/__init__.py
- minos/common/model/__init__.py
- minos/common/model/command.py
- minos/common/model/command_reply.py
- tests/test_common/test_model/test_command.py
- tests/test_common/test_model/test_command_reply.py
Create CommandReply Model.
Modify Command Model: add saga_id and task_id.
> Command and CommandReply

- minos/common/configuration/config.py
- tests/test_common/test_configuration/test_config.py
- tests/test_config.yml
```yaml
saga:
- name: AddOrder
controller: minos.services.OrderService
action: add_order
- name: DeleteOrder
controller: minos.services.OrderService
action: delete_order
```
> MinosConfig SAGA configuration

- minos/common/configuration/config.py
- tests/test_common/test_configuration/test_config.py
- tests/test_config.yml
Add items and queue to Saga MinosConfig #188
> Add items and queue to Saga MinosConfig

- minos/common/model/abc/model.py
- tests/test_common/test_model/test_abc/test_model.py
> #195 (Implement `avro_str`-like methods)

- poetry.lock
- pyproject.toml
> #238 (remove `six` dependency)

- minos/common/saga.py
- tests/test_common/test_saga.py
> #240 saga manager kwargs

- .gitignore
> #236 (update gitignore)

- minos/common/configuration/config.py
- tests/test_common/test_configuration/test_config.py
- tests/test_common/test_configuration/test_config_parameterized.py
- tests/test_common/test_configuration/test_config_with_env.py
* Extracted two new test cases to cover testing with environment variables and parameterized input.
* Refactored MinosConfigCreation into setUp.
> ISSUE #252

- HISTORY.md
- Makefile
- docs/authors.rst
- docs/conf.py
- docs/history.rst
- docs/index.rst
- docs/readme.rst
- docs/usage.rst
- poetry.lock
- pyproject.toml
> ISSUE #247

- tests/docker-compose.yml
* Added docker-compose for easy testing.
> ISSUE #260

- minos/common/model/abc/model.py
- minos/common/model/command.py
- minos/common/model/command_reply.py
- minos/common/model/event.py
- tests/test_common/test_model/test_command.py
- tests/test_common/test_model/test_command_reply.py
- tests/test_common/test_saga.py
> #273 (redefine `minos.common.Command` and `minos.common.CommandReply` attributes)

- minos/common/importlib.py
- tests/test_common/test_importlib.py
> #292 (improve `import_module` and `classname` functions)

- minos/common/testing.py
> #294 (Fix bug related with database tear down)

- minos/common/model/aggregate.py
> #285 (improve aggregate type hinting)

- minos/common/protocol/avro/base.py
- tests/test_common/test_protocol/test_avro/test_base.py
Recover avro_schema from byte-encoded avro instance #302
> Recover avro schema

- minos/common/__init__.py
- minos/common/exceptions.py
- minos/common/model/aggregate.py
- tests/test_common/test_model/test_abc/test_fields.py
- tests/test_common/test_model/test_abc/test_model/test_avro.py
- tests/test_common/test_model/test_aggregate/test_base.py
- tests/test_common/test_model/test_aggregate/test_broker.py
- tests/test_common/test_model/test_aggregate/test_non_provided.py
- tests/test_common/test_model/test_aggregate/test_with_posgres.py
- tests/test_common/test_networks.py
- tests/test_common/test_repository/test_entries.py
- tests/test_common/test_repository/test_pg.py
- tests/test_common/test_service.py
- tests/utils.py
> #268 (publish `minos.common.Aggregate` changes over `minos.common.MinosBroker`)

- minos/common/__init__.py
- minos/common/model/aggregate.py
- minos/common/repository/__init__.py
- minos/common/repository/abc.py
- minos/common/repository/entries.py
- minos/common/repository/memory.py
- minos/common/repository/pg.py
- tests/test_common/test_model/test_aggregate/test_base.py
- tests/test_common/test_model/test_aggregate/test_with_posgres.py
- tests/test_common/test_repository/test_entries.py
- tests/test_common/test_repository/test_memory.py
- tests/test_common/test_repository/test_pg.py
- tests/utils.py
> #320 (simplify `repository` class names)

- minos/common/model/abc/model.py
> #325 (equality and `fields` ordering on `minos.common.MinosModel`)

- minos/common/model/declarative/aggregate/diff.py
- minos/common/model/declarative/aggregate/model.py
- minos/common/model/dynamic/abc.py
- minos/common/repository/abc.py
- minos/common/repository/entries.py
- minos/common/snapshot/memory.py
- minos/common/snapshot/pg/builders.py
- tests/test_common/test_model/test_declarative/test_aggregate/test_diff.py
- tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_broker.py
- tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_differences.py
- tests/test_common/test_repository/test_entries.py
- tests/test_common/test_snapshots/test_pg/test_builders.py
- tests/test_common/test_snapshots/test_pg/test_readers.py
> #84 (`minos.common.AggregateDiff` integration with `minos.common.MinosRepository` and `minos.common.MinosSnapshot`)

- minos/common/meta.py
- minos/common/model/fields/avro_data_decoder.py
- minos/common/model/fields/avro_data_encoder.py
- minos/common/model/fields/avro_schema_decoder.py
- minos/common/model/fields/avro_schema_encoder.py
- minos/common/repository/entries.py
- minos/common/snapshot/entries.py
> #272 (Remove implicit `object` inheritance)

- minos/common/exceptions.py
- minos/common/snapshot/entries.py
- minos/common/snapshot/pg/abc.py
- minos/common/snapshot/pg/builders.py
- minos/common/snapshot/pg/snapshot.py
- tests/test_common/test_snapshots/test_pg/test_builders.py
- tests/test_common/test_snapshots/test_pg/test_readers.py
> #331 (improve `Aggregate` deletion behaviour on `Snapshot`)

- minos/common/model/declarative/aggregate/model.py
- tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_base.py
> #314 (Add `minos.common.Aggregate.save` method)

- minos/common/model/declarative/aggregate/model.py
- tests/test_common/test_model/test_declarative/test_abc/test_avro.py
- tests/test_common/test_model/test_declarative/test_aggregate/test_diff.py
- tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_base.py
- tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_differences.py
- tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_not_provided.py
- tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_with_posgres.py
- tests/test_common/test_model/test_dynamic/test_diff.py
- tests/test_common/test_model/test_fields/test_fields.py
- tests/test_common/test_snapshots/test_entries.py
- tests/test_common/test_snapshots/test_pg/test_builders.py
- tests/test_common/test_snapshots/test_pg/test_readers.py
> #344 (Simplify `minos.common.Aggregate` constructor)

- minos/common/injectors.py
- minos/common/launchers.py
- minos/common/setup.py
- minos/common/storage/lmdb.py
- tests/utils.py
> #347 (Fix `DependencyInjector`)

- minos/common/configuration/config.py
- minos/common/injectors.py
- minos/common/launchers.py
- minos/common/model/fields/avro_data_encoder.py
- tests/test_common/test_configuration/test_config.py
- tests/test_common/test_injectors.py
- tests/test_common/test_launchers.py
> #354 (Fix bug related with `avro_data` and `datetime`'s timezones)

- minos/common/exceptions.py
- minos/common/model/declarative/__init__.py
- minos/common/model/declarative/value_object.py
- tests/test_common/test_model/test_declarative/test_value_object.py
- tests/value_objects.py
> Issue 395 add valueobject

- minos/common/__init__.py
- minos/common/model/__init__.py
- minos/common/model/declarative/__init__.py
- minos/common/model/declarative/subaggregate/__init__.py
- minos/common/model/declarative/subaggregate/model.py
- minos/common/model/serializers/avro_data_decoder.py
- minos/common/model/types/__init__.py
- minos/common/model/types/comparators.py
- tests/subaggregate_classes.py
- tests/test_common/test_model/test_declarative/test_subaggregate/test_model.py
- tests/test_common/test_model/test_serializers/test_avro_data_decoder.py
Create SubAggregate Class #398
> Create SubAggregate Class

- .github/workflows/python-tests.yml
Simplify postgres config on Github Actions #411
> Simplify postgres config on Github Actions

- minos/common/saga.py
- tests/test_common/test_saga.py
┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/15xp915) by [Unito](https://www.unito.io)
> #423 (Improve `MinosSagaManager.run` interface)

- minos/common/launchers.py
┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/15zrz8m) by [Unito](https://www.unito.io)
> #428 (Fix `DateFormat` bug related with `logging`)

- minos/common/__init__.py
- minos/common/exceptions.py
- minos/common/networks.py
- tests/test_common/test_exceptions.py
- tests/test_common/test_networks.py
- tests/utils.py
┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/15zt0ay) by [Unito](https://www.unito.io)
> #430 (define `MinosHandler` interface)

- minos/common/model/declarative/aggregate/model.py
- minos/common/snapshot/abc.py
- minos/common/snapshot/memory.py
- minos/common/snapshot/pg/builders.py
- minos/common/snapshot/pg/snapshot.py
- tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_base.py
- tests/test_common/test_snapshots/test_pg/test_readers.py
- tests/utils.py
┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/15ztrtv) by [Unito](https://www.unito.io)
> #349 (Improve typing to be a `set[UUID]` instead of a `list[UUID]`)

- minos/common/__init__.py
- minos/common/pools.py
- tests/test_common/test_pools.py
┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/17nw6xe) by [Unito](https://www.unito.io)
> #439 (Add `minos.common.MinosPool`)

- minos/common/storage/lmdb.py
┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/185umeh) by [Unito](https://www.unito.io)
> #445 (Increase default `minos.common.MinosStorageLmdb.map_size` to 1GB.

- minos/common/__init__.py
- minos/common/configuration/__init__.py
- minos/common/configuration/config.py
- tests/test_common/test_configuration/test_config.py
- tests/test_config.yml
┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/185umwu) by [Unito](https://www.unito.io)
> #444 (Remove `rest.endpoints` from `minos.common.MinosConfig`)

- minos/common/__init__.py
- minos/common/configuration/__init__.py
- minos/common/configuration/config.py
- tests/test_common/test_configuration/test_config.py
- tests/test_common/test_configuration/test_config_parameterized.py
- tests/test_common/test_configuration/test_config_with_env.py
- tests/test_config.yml
┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/185w3ar) by [Unito](https://www.unito.io)
> #450 (Remove `discovery.endpoints` from `minos.common.MinosConfig`)

- .github/workflows/python-tests.yml
- minos/common/configuration/config.py
- minos/common/testing.py
- tests/test_common/test_configuration/test_config.py
- tests/test_common/test_configuration/test_config_parameterized.py
- tests/test_common/test_configuration/test_config_with_env.py
- tests/test_config.yml
Create common broker entry on minos.common.MinosConfig #453
┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/18bz93x) by [Unito](https://www.unito.io)
> Create common broker entry on minos.common.MinosConfig

- minos/common/launchers.py
- tests/utils.py
┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/18dy03x) by [Unito](https://www.unito.io)
> #460 (Improve `minos.common.EntrypointLauncher.launch` method)

- minos/common/model/types/builders.py
- tests/test_common/test_model/test_types/test_builders.py
┆Issue is synchronized with this [ClickUp task](https://app.clickup.com/t/18dywgf) by [Unito](https://www.unito.io)
> #462 (Fix bug related with empty iterables and `TypeHintBuilder`)

- minos/common/__init__.py
- minos/common/exceptions.py
- minos/common/model/__init__.py
- minos/common/model/declarative/__init__.py
- minos/common/model/declarative/aggregate/__init__.py
- minos/common/model/declarative/aggregate/actions.py
- minos/common/model/declarative/aggregate/diff.py
- minos/common/model/serializers/avro_data_decoder.py
- minos/common/repository/__init__.py
- minos/common/repository/abc.py
- minos/common/repository/entries.py
- minos/common/snapshot/memory.py
- minos/common/snapshot/pg/builders.py
- tests/test_common/test_exceptions.py
- tests/test_common/test_model/test_declarative/test_aggregate/test_actions.py
- tests/test_common/test_model/test_declarative/test_aggregate/test_diff.py
- tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_broker.py
- tests/test_common/test_model/test_declarative/test_aggregate/test_model/test_differences.py
- tests/test_common/test_model/test_declarative/test_networks.py
- tests/test_common/test_repository/test_entries.py
- tests/test_common/test_repository/test_memory.py
- tests/test_common/test_repository/test_pg.py
- tests/test_common/test_snapshots/test_pg/test_builders.py
┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1afz8je) by [Unito](https://www.unito.io)
> #402 (Refactor `RepositoryAction` into `AggregateAction`)

- minos/common/model/declarative/networks.py
- tests/test_common/test_model/test_declarative/test_networks.py
Closes #395
┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1afza9f) by [Unito](https://www.unito.io)
> Add `User` to `Command` - ISSUE #395

- minos/common/model/declarative/aggregate/diff.py
- tests/test_common/test_model/test_declarative/test_aggregate/test_diff.py
Add decompose method to minos.common.AggregateDiff #487
> Add decompose method to minos.common.AggregateDiff

- minos/common/__init__.py
- minos/common/model/__init__.py
- minos/common/model/declarative/__init__.py
- minos/common/model/declarative/aggregate/model.py
- minos/common/model/declarative/aggregate/ref.py
- minos/common/model/declarative/entities.py
- tests/test_common/test_model/test_declarative/test_entities.py
> Create Entity class

- minos/common/configuration/config.py
- tests/test_common/test_configuration/test_config.py
- tests/test_common/test_configuration/test_config_parameterized.py
- tests/test_common/test_configuration/test_config_with_env.py
- tests/test_config.yml
> #578 - Added type to discovery.
